spring.application.name=QLLinhKienDienTu

# K?t n?i database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QL_LINHKIEN_DIENTU;integratedSecurity=true;encrypt=true;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# C?u hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect